In [2]:
import torch 
import torch.nn as nn 
import numpy  as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import time 
import math



In [ ]:

# Check if GPU is available
print(f"PyTorch version: {torch.__version__}")
print(f"GPU available: {torch.cuda.is_available()}")            
if torch.cuda.is_available():
    print(f"GPU name: {torch.cuda.get_device_name(0)}")
else:
    print("⚠️ No GPU detected. Go to Runtime → Change runtime type → GPU")
    print("   (Some demos will still work, just slower)")

print("\n✅ Setup complete! Ready to go.")

PyTorch version: 2.9.1+cpu
GPU available: False
⚠️ No GPU detected. Go to Runtime → Change runtime type → GPU
   (Some demos will still work, just slower)

✅ Setup complete! Ready to go.


In [4]:
# A scalar — just a number
scalar = torch.tensor(42.0)
print(f"Scalar: {scalar}")
print(f"  Shape: {scalar.shape}")      # torch.Size([])
print(f"  Dimensions: {scalar.dim()}")  # 0
print()

# A vector — a list of numbers
vector = torch.tensor([1.0, 2.0, 3.0, 4.0])
print(f"Vector: {vector}")
print(f"  Shape: {vector.shape}")      # torch.Size([4])
print(f"  Dimensions: {vector.dim()}")  # 1
print()

# A matrix — a grid of numbers
matrix = torch.tensor([[1, 2, 3],
                        [4, 5, 6]])
print(f"Matrix:\n{matrix}")
print(f"  Shape: {matrix.shape}")      # torch.Size([2, 3])
print(f"  Dimensions: {matrix.dim()}")  # 2
print()

# A 3D tensor — a cube of numbers
tensor_3d = torch.zeros(2, 3, 4)
print(f"3D Tensor shape: {tensor_3d.shape}")    # [2, 3, 4]
print(f"  Dimensions: {tensor_3d.dim()}")        # 3
print()

# A 4D tensor — like a batch going through multi-head attention
tensor_4d = torch.zeros(8, 12, 3, 64)
print(f"4D Tensor shape: {tensor_4d.shape}")    # [8, 12, 3, 64]
print(f"  That's: 8 sentences × 12 heads × 3 tokens × 64 dims")

Scalar: 42.0
  Shape: torch.Size([])
  Dimensions: 0

Vector: tensor([1., 2., 3., 4.])
  Shape: torch.Size([4])
  Dimensions: 1

Matrix:
tensor([[1, 2, 3],
        [4, 5, 6]])
  Shape: torch.Size([2, 3])
  Dimensions: 2

3D Tensor shape: torch.Size([2, 3, 4])
  Dimensions: 3

4D Tensor shape: torch.Size([8, 12, 3, 64])
  That's: 8 sentences × 12 heads × 3 tokens × 64 dims


In [6]:
z = torch.zeros(3, 4)
print(f"Tensor z:\n{z}"
      )

Tensor z:
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [8]:
o = torch.ones(3, 4 )
print(f"Tensor o:\n{o}")

Tensor o:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [10]:
r = torch.rand(3,4)
print(f"Tensor r:\n{r}")

Tensor r:
tensor([[0.4695, 0.0558, 0.1085, 0.4178],
        [0.6937, 0.5787, 0.7071, 0.4318],
        [0.5470, 0.2788, 0.5612, 0.0614]])


In [11]:
seq = torch.arange(0 ,10)
seq

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
lin = torch.linspace(0 , 1, 7)
print(lin)

tensor([0.0000, 0.1667, 0.3333, 0.5000, 0.6667, 0.8333, 1.0000])


In [15]:
# Real-world shapes in deep learning:
batch_size = 8
seq_len = 128
embed_dim = 768
num_heads = 12
head_dim = embed_dim // num_heads  # 64

In [16]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [19]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [20]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler


In [21]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [22]:
# scaling the data 
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [23]:
encoder = LabelEncoder()
y_train_encoded = encoder.fit_transform(y_train)
y_test_encoded = encoder.transform(y_test)

In [24]:
X_train_tensor = torch.from_numpy(X_train_scaled)
X_test_tensor = torch.from_numpy(X_test_scaled)
y_train_tensor = torch.from_numpy(y_train_encoded)
y_test_tensor = torch.from_numpy(y_test_encoded)

In [35]:
from numpy import dtype


class MySimpleNN():

    def __init__(self , X):
        
        self.weights = torch.rand(X.shape[1] , 1 , requires_grad=True , dtype = torch.float64)
        self.bias = torch.rand(1 , dtype = torch.float64 , requires_grad=True)

    def forward(self , X):
        z = torch.matmul(X , self.weights) + self.bias
        y_pred = torch.sigmoid(z)

        return y_pred

    def loss(self , y_pred , y):
        # clamp prediction to avoid log(0) error 
        epsilon = 1e-8
        y_pred = torch.clamp(y_pred , epsilon , 1-epsilon)

        loss = -(y * torch.log(y_pred) + (1-y) * torch.log(1-y_pred))
        loss = loss.mean() #  i dont know why are we doing this but i wil find out 
        return loss 
    
    
        

In [40]:
learning_rate = 0.1
epochs = 1000

In [41]:
X_train_tensor.shape

torch.Size([455, 30])

In [42]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.365532741316607
Epoch: 2, Loss: 3.232096588953783
Epoch: 3, Loss: 3.095058373376739
Epoch: 4, Loss: 2.9475718633271466
Epoch: 5, Loss: 2.794846163156493
Epoch: 6, Loss: 2.6393676012553504
Epoch: 7, Loss: 2.4845871573025624
Epoch: 8, Loss: 2.333884410516595
Epoch: 9, Loss: 2.184217317882972
Epoch: 10, Loss: 2.0393855529797147
Epoch: 11, Loss: 1.8974695041763132
Epoch: 12, Loss: 1.7561881254838732
Epoch: 13, Loss: 1.6207425238501598
Epoch: 14, Loss: 1.4963674025253553
Epoch: 15, Loss: 1.384046491437698
Epoch: 16, Loss: 1.2845629925171067
Epoch: 17, Loss: 1.1983948443029326
Epoch: 18, Loss: 1.1256019940197033
Epoch: 19, Loss: 1.065720463090669
Epoch: 20, Loss: 1.0176996453627982
Epoch: 21, Loss: 0.9799467489311406
Epoch: 22, Loss: 0.9505166929712696
Epoch: 23, Loss: 0.9274025448795855
Epoch: 24, Loss: 0.9088150636564919
Epoch: 25, Loss: 0.8933472535014988
Epoch: 26, Loss: 0.8799976387156528
Epoch: 27, Loss: 0.8681024452958093
Epoch: 28, Loss: 0.8572414921741852
Epoch: 29

In [56]:
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.2).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f"accuracy : {accuracy.item()}")

accuracy : 0.4385964870452881


In [63]:
# tensor GPU operations 
torch.cuda.is_available()


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

a = torch.tensor([1.0, 2.0, 3.0], device=device)
# this is how to create a tenso on GPU 
b = torch.tensor([1.0, 2.0, 3.0], device=device)


a.to(device)

cpu


tensor([1., 2., 3.])

In [67]:
b = torch.rand(2,3,4)

b = b.permute(2, 0 ,1)

b.shape

torch.Size([4, 2, 3])

In [70]:
# autodgrad in pytorch in python 
# provides a new way to compute gradients that means : it provides automatic gradients computation for tensor operations 
# it enables graduesbt computation which is essential forthe training ml model using the optimization algorithms like gradient desent 

X = torch.tensor([[1.0, 2.0], [3.0, 4.0]], requires_grad=True)
x = torch.tensor(3.0, requires_grad=True)
y = x**2


In [71]:
y.backward()

In [72]:
x.grad

tensor(6.)

In [73]:
import torch

# Inputs
x = torch.tensor(6.7)  # Input feature
y = torch.tensor(0.0)  # True label (binary)

w = torch.tensor(1.0)  # Weight
b = torch.tensor(0.0)  # Bias

In [74]:
# Binary Cross-Entropy Loss for scalar
def binary_cross_entropy_loss(prediction, target):
    epsilon = 1e-8  # To prevent log(0)
    prediction = torch.clamp(prediction, epsilon, 1 - epsilon)
    return -(target * torch.log(prediction) + (1 - target) * torch.log(1 - prediction))

In [75]:
# Forward pass
z = w * x + b  # Weighted sum (linear part)
y_pred = torch.sigmoid(z)  # Predicted probability

# Compute binary cross-entropy loss
loss = binary_cross_entropy_loss(y_pred, y)

In [76]:
# Derivatives:
# 1. dL/d(y_pred): Loss with respect to the prediction (y_pred)
dloss_dy_pred = (y_pred - y)/(y_pred*(1-y_pred))

# 2. dy_pred/dz: Prediction (y_pred) with respect to z (sigmoid derivative)
dy_pred_dz = y_pred * (1 - y_pred)

# 3. dz/dw and dz/db: z with respect to w and b
dz_dw = x  # dz/dw = x
dz_db = 1  # dz/db = 1 (bias contributes directly to z)

dL_dw = dloss_dy_pred * dy_pred_dz * dz_dw
dL_db = dloss_dy_pred * dy_pred_dz * dz_db

In [77]:
print(f"Manual Gradient of loss w.r.t weight (dw): {dL_dw}")
print(f"Manual Gradient of loss w.r.t bias (db): {dL_db}")

Manual Gradient of loss w.r.t weight (dw): 6.691762447357178
Manual Gradient of loss w.r.t bias (db): 0.998770534992218


In [78]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)

In [79]:
w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

In [82]:
z = w*x + b
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [83]:
y_pred = torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [84]:
loss = binary_cross_entropy_loss(y_pred, y)
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [86]:
loss.backward()

In [87]:
w.grad


tensor(6.6918)

In [88]:
b.grad

tensor(0.9988)

In [89]:
# options to clear the gradients  : why ? beacuse they consume memory for large models and also prevent the gradient accumulation 
# clearing grad
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [90]:
y = x ** 2
y

tensor(4., grad_fn=<PowBackward0>)

In [91]:
y.backward()

In [92]:
x.grad

tensor(4.)

In [93]:
x.grad.zero_()

tensor(0.)

In [94]:
# disable gradient tracking
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [95]:
y = x ** 2
y

tensor(4., grad_fn=<PowBackward0>)

In [96]:
y.backward()

x.grad

tensor(4.)

In [97]:
# there are 3 ways to clean the gradients : # option 1 - requires_grad_(False)
# option 2 - detach()
# option 3 - torch.no_grad()

In [99]:
x.requires_grad_(False)


tensor(2.)

In [104]:
x.detach()


tensor(2.)

In [107]:
y.detach()

y.requires_grad

True

### learning about the nn module 


In [126]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features , 1  )
    self.sigmoid = nn.Sigmoid()

  def forward(self , features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out 



In [127]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward(features) 
model(features)

# notice we are not doing this model.forward(features) but we are doing this model(features) 

tensor([[0.4666],
        [0.5421],
        [0.5126],
        [0.5069],
        [0.5088],
        [0.4758],
        [0.4586],
        [0.4578],
        [0.4551],
        [0.4930]], grad_fn=<SigmoidBackward0>)

In [129]:
model.linear.weight

Parameter containing:
tensor([[-0.3855,  0.3159,  0.2854, -0.0171,  0.0716]], requires_grad=True)

In [130]:
model.linear.bias

Parameter containing:
tensor([-0.2006], requires_grad=True)

In [131]:
# torchinfo 

from torchinfo import summary

summary(model , input_size = (10 , 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

### changing the setup 

In [133]:
# 5 inputs ----> 3 neurons ----> 1 neuron ----> 1 output 
# let's implement this using the nn module 


In [140]:
class MyNewNN(nn.Module):

    def __init__(self, num_features):

        super().__init__()
        self.linear1 = nn.Linear(num_features , 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()


    def forward(self , features):

        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)

        return out 
    



In [141]:
# create dataset
features = torch.rand(10,5)

# create model
model = MyNewNN(features.shape[1])

# call model for forward pass
# model.forward(features) 
model(features)


tensor([[0.5659],
        [0.5448],
        [0.5614],
        [0.5581],
        [0.5842],
        [0.5798],
        [0.5451],
        [0.5581],
        [0.5842],
        [0.5843]], grad_fn=<SigmoidBackward0>)

In [143]:
model.linear1.weight

Parameter containing:
tensor([[-0.1989, -0.3464,  0.2463, -0.0299, -0.1531],
        [ 0.0101,  0.0451, -0.2301,  0.2007, -0.1498],
        [-0.1211, -0.1956,  0.2753,  0.2575,  0.3027]], requires_grad=True)

In [147]:
model.linear2.bias

Parameter containing:
tensor([0.3402], requires_grad=True)